/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({ id: '/chat', path: '/chat', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({ id: '/feed', path: '/feed', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({ id: '/logs', path: '/logs', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AuthenticatedRoute } as any)
const ApiChatRoute = ApiChatRouteImport.update({ id: '/api/chat', path: '/api/chat', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/chat' | '/feed' | '/dashboard' | '/logs' | '/settings' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chat' | '/feed' | '/dashboard' | '/logs' | '/settings' | '/api/chat'
  id: '__root__' | '/' | '/_authenticated' | '/_authenticated/' | '/auth' | '/_authenticated/chat' | '/_authenticated/feed' | '/_authenticated/dashboard' | '/_authenticated/logs' | '/_authenticated/settings' | '/api/chat'
  fileRoutesById: FileRoutesById
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}
const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedChatRoute,
  AuthenticatedFeedRoute,
  AuthenticatedDashboardRoute,
  AuthenticatedLogsRoute,
  AuthenticatedSettingsRoute,
}
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute,
  ApiChatRoute,
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: ''; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/': { id: '/_authenticated/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof AuthenticatedIndexRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/chat': { id: '/_authenticated/chat'; path: '/chat'; fullPath: '/chat'; preLoaderRoute: typeof AuthenticatedChatRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/feed': { id: '/_authenticated/feed'; path: '/feed'; fullPath: '/feed'; preLoaderRoute: typeof AuthenticatedFeedRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/logs': { id: '/_authenticated/logs'; path: '/logs'; fullPath: '/logs'; preLoaderRoute: typeof AuthenticatedLogsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/settings': { id: '/_authenticated/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AuthenticatedSettingsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/api/chat': { id: '/api/chat'; path: '/api/chat'; fullPath: '/api/chat'; preLoaderRoute: typeof ApiChatRouteImport; parentRoute: typeof rootRouteImport }
  }
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
